#597ee5e0530947ed55734d2251fff219753101ac36c4d2a887a3444427a8bab3-f823fcdcb3f48fa1

# Generated by CuBIE. Edit the system definition instead.
from cubie.cuda_simsafe import cuda, int32
import math
from cubie.cuda_simsafe import *


# AUTO-GENERATED DXDT FACTORY
def dxdt_factory(precision, lineinfo=None):
    """Auto-generated dxdt factory."""
    
    @cuda.jit(
        # (precision[::1],
        #  precision[::1],
        #  precision[::1],
        #  precision[::1],
        #  precision[::1],
        #  precision),
        device=True,
        inline=True,
        **get_jit_kwargs(lineinfo))
    def dxdt(state, parameters, drivers, observables, out, t):
        out[0] = -precision(10)*state[0] + precision(10)*state[1]
        out[1] = -state[1] + state[0]*(parameters[0] - state[2])
        out[2] = -precision(2.6666666666666665)*state[2] + state[0]*state[1]
    
    return dxdt

# AUTO-GENERATED OBSERVABLES FACTORY
def observables_factory(precision, lineinfo=None):
    """Auto-generated observables factory."""
    @cuda.jit(
        # (precision[::1],
        #  precision[::1],
        #  precision[::1],
        #  precision[::1],
        #  precision),
        device=True,
        inline=True,
        **get_jit_kwargs(lineinfo))
    def get_observables(state, parameters, drivers, observables, t):
        pass
    
    return get_observables

# AUTO-GENERATED DIAGONAL JACOBI PRECONDITIONER FACTORY
def jacobi_preconditioner_cached_s794e04862751a58d890a3f2d5a91e545a15f9d7c4946ddc47920dc598d2272b0(precision, order=0, lineinfo=None):
    """Auto-generated diagonal Jacobi preconditioner.
    Computes the diagonal ``D = diag(beta * M - gamma * a_ij * h *
    J)`` and applies pointwise inversion: ``out[i] = v[i] / D[i]``.
    With ``order > 0`` the same splitting carries a truncated
    series, ``out = sum_[k=0..order] (D^[-1] N)^k D^[-1] v`` with
    ``N = gamma * a_ij * h * (J - diag(J))``.
    Returns device function:
      preconditioner(
          state, parameters, drivers, cached_aux, base_state, t, h, a_ij, v, out, jvp
      )
    """
    _cubie_codegen_order = int32(order)
    if order > 0:
        @cuda.jit(
            device=True,
            inline=True,
            **get_jit_kwargs(lineinfo))
        def preconditioner(state, parameters, drivers, cached_aux, base_state, t, _cubie_codegen_h, _cubie_codegen_a_ij, v, out, jvp):
            _cubie_codegen_jac_scale = precision(0.7886751294136047)*_cubie_codegen_h
            _cse0 = precision(10)*_cubie_codegen_jac_scale + precision(1.0)
            _cse1 = _cubie_codegen_jac_scale + precision(1.0)
            _cse2 = precision(2.6666666666666665)*_cubie_codegen_jac_scale + precision(1.0)
            _cubie_codegen_inv_diag_0 = (precision(1)/selp(math.fabs(_cse0) >= precision(1e-16), _cse0, precision(1e-16)))
            _cubie_codegen_inv_diag_1 = (precision(1)/selp(math.fabs(_cse1) >= precision(1e-16), _cse1, precision(1e-16)))
            _cubie_codegen_inv_diag_2 = (precision(1)/selp(math.fabs(_cse2) >= precision(1e-16), _cse2, precision(1e-16)))
            out[0] = _cubie_codegen_inv_diag_0*v[0]
            out[1] = _cubie_codegen_inv_diag_1*v[1]
            out[2] = _cubie_codegen_inv_diag_2*v[2]
            _cubie_codegen_h_eff = precision(0.7886751294136047) * _cubie_codegen_h
            _cubie_codegen_j_1_0 = parameters[0] - state[2]
            _cubie_codegen_j_1_2 = -state[0]
            for _ in range(_cubie_codegen_order):
                jvp[0] = -precision(10)*out[0] + precision(10)*out[1]
                jvp[2] = -precision(2.6666666666666665)*out[2] + state[0]*out[1] + state[1]*out[0]
                jvp[1] = -out[1] + _cubie_codegen_j_1_0*out[0] + _cubie_codegen_j_1_2*out[2]
                out[0] = out[0] + (v[0] + _cubie_codegen_h_eff * jvp[0] - out[0]) * _cubie_codegen_inv_diag_0
                out[1] = out[1] + (v[1] + _cubie_codegen_h_eff * jvp[1] - out[1]) * _cubie_codegen_inv_diag_1
                out[2] = out[2] + (v[2] + _cubie_codegen_h_eff * jvp[2] - out[2]) * _cubie_codegen_inv_diag_2
    else:
        @cuda.jit(
            device=True,
            inline=True,
            **get_jit_kwargs(lineinfo))
        def preconditioner(state, parameters, drivers, cached_aux, base_state, t, _cubie_codegen_h, _cubie_codegen_a_ij, v, out, jvp):
            _cubie_codegen_jac_scale = precision(0.7886751294136047)*_cubie_codegen_h
            _cse0 = precision(10)*_cubie_codegen_jac_scale + precision(1.0)
            _cse1 = _cubie_codegen_jac_scale + precision(1.0)
            _cse2 = precision(2.6666666666666665)*_cubie_codegen_jac_scale + precision(1.0)
            out[0] = v[0]/selp(math.fabs(_cse0) >= precision(1e-16), _cse0, precision(1e-16))
            out[1] = v[1]/selp(math.fabs(_cse1) >= precision(1e-16), _cse1, precision(1e-16))
            out[2] = v[2]/selp(math.fabs(_cse2) >= precision(1e-16), _cse2, precision(1e-16))
    return preconditioner
# Buffer sizes read by the helper registry
jacobi_preconditioner_cached_s794e04862751a58d890a3f2d5a91e545a15f9d7c4946ddc47920dc598d2272b0.aux_count = None
jacobi_preconditioner_cached_s794e04862751a58d890a3f2d5a91e545a15f9d7c4946ddc47920dc598d2272b0.lu_nnz = None

# AUTO-GENERATED JACOBIAN PREPARATION FACTORY
def prepare_jac_cached_sf65da0187bd13079fb874b415be7d9deb7fb06ca0496091ada2e91444dcc4b10(precision, lineinfo=None):
    """Auto-generated Jacobian auxiliary preparation.
    Populates cached_aux with intermediate Jacobian values.
    Signature (state, parameters, drivers, t, h, cached_aux)
    -> int32 status; always returns int32(0).
    """
    @cuda.jit(
        device=True,
        inline=True,
        **get_jit_kwargs(lineinfo))
    def prepare_jac(state, parameters, drivers, t, h, cached_aux):
        pass
        return int32(0)
    return prepare_jac
# Buffer sizes read by the helper registry
prepare_jac_cached_sf65da0187bd13079fb874b415be7d9deb7fb06ca0496091ada2e91444dcc4b10.aux_count = 0
prepare_jac_cached_sf65da0187bd13079fb874b415be7d9deb7fb06ca0496091ada2e91444dcc4b10.lu_nnz = None

# AUTO-GENERATED LINEAR OPERATOR FACTORY
def linear_operator_cached_s70ea5cf2fd47e1f9025f6fa0eb7fc9b50d8603b0ab0a1aee6a3eaca54dad901a(precision, lineinfo=None):
    """Auto-generated linear operator.
    Computes out = beta * (M @ v) - gamma * a_ij * h * (J @ v)
    with beta and gamma baked in as numeric literals.
    Returns device function:
      operator_apply(
          state, parameters, drivers, cached_aux, base_state, t, h, a_ij, v, out
      )
    """
    @cuda.jit(
        device=True,
        inline=True,
        **get_jit_kwargs(lineinfo))
    def operator_apply(
        state, parameters, drivers, cached_aux, base_state, t,
        _cubie_codegen_h, _cubie_codegen_a_ij, v, out,
    ):
        _cubie_codegen_j_1_0 = parameters[0] - state[2]
        _cubie_codegen_j_1_2 = -state[0]
        _cubie_codegen_jac_scale = precision(0.7886751294136047)*_cubie_codegen_h
        out[0] = v[0] - _cubie_codegen_jac_scale*(-precision(10)*v[0] + precision(10)*v[1])
        out[1] = v[1] - _cubie_codegen_jac_scale*(-v[1] + _cubie_codegen_j_1_0*v[0] + _cubie_codegen_j_1_2*v[2])
        out[2] = v[2] - _cubie_codegen_jac_scale*(-precision(2.6666666666666665)*v[2] + state[0]*v[1] + state[1]*v[0])
    return operator_apply
# Buffer sizes read by the helper registry
linear_operator_cached_s70ea5cf2fd47e1f9025f6fa0eb7fc9b50d8603b0ab0a1aee6a3eaca54dad901a.aux_count = None
linear_operator_cached_s70ea5cf2fd47e1f9025f6fa0eb7fc9b50d8603b0ab0a1aee6a3eaca54dad901a.lu_nnz = None

# AUTO-GENERATED TIME-DERIVATIVE FACTORY
def time_derivative_rhs_plain_se6cc8240e2650be8d67c96c840124016c32ca449381b6b9f5d45cfb9468103ce(precision, lineinfo=None):
    """Auto-generated time-derivative factory."""
    @cuda.jit(
        # (precision[::1],
        #  precision[::1],
        #  precision[::1],
        #  precision[::1],
        #  precision[::1],
        #  precision[::1],
        #  precision),
        device=True,
        inline=True,
        **get_jit_kwargs(lineinfo))
    def time_derivative_rhs(
        state, parameters, drivers, driver_dt, observables, out, t
    ):
        out[0] = precision(0)
        out[1] = precision(0)
        out[2] = precision(0)

    return time_derivative_rhs
# Buffer sizes read by the helper registry
time_derivative_rhs_plain_se6cc8240e2650be8d67c96c840124016c32ca449381b6b9f5d45cfb9468103ce.aux_count = None
time_derivative_rhs_plain_se6cc8240e2650be8d67c96c840124016c32ca449381b6b9f5d45cfb9468103ce.lu_nnz = None

# AUTO-GENERATED IDENTITY PRECONDITIONER FACTORY
def no_preconditioner_plain_seba9c924e5da83229d1f40acbdbc42359fec9cbbe10ff16f61e284753d3abd0f(precision, order=0, lineinfo=None):
    """Identity preconditioner: copies ``v`` into ``out``."""
    _cubie_codegen_n = int32(3)
    @cuda.jit(
        device=True,
        inline=True,
        **get_jit_kwargs(lineinfo))
    def preconditioner(
        state, parameters, drivers, cached_aux, base_state, t, _cubie_codegen_h, _cubie_codegen_a_ij, v, out, jvp
    ):
        for i in range(_cubie_codegen_n):
            out[i] = v[i]
    return preconditioner
# Buffer sizes read by the helper registry
no_preconditioner_plain_seba9c924e5da83229d1f40acbdbc42359fec9cbbe10ff16f61e284753d3abd0f.aux_count = None
no_preconditioner_plain_seba9c924e5da83229d1f40acbdbc42359fec9cbbe10ff16f61e284753d3abd0f.lu_nnz = None

# AUTO-GENERATED DIRECT LU SOLVE FACTORY
def lu_solve_cached_scd8c35dcc3f58b01a730627fae41722ecc7038de659bc3e21147fe1246c3f9e1(precision, lineinfo=None):
    """Auto-generated direct sparse LU solve.
    Solves (beta * M - gamma * a_ij * h * J) @ x = rhs with a
    static symbolic factorisation; beta and gamma are baked in
    as numeric literals and J is evaluated at
    state, auxiliaries from cached_aux.
    Returns device function:
      lu_solve(state, parameters, drivers, cached_aux, base_state,
               t, h, a_ij, rhs, x, factor) -> int32
    Pivots are magnitude-floored; always returns int32(0).
    rhs is read-only; x is written unconditionally.
    """
    @cuda.jit(
        device=True,
        inline=True,
        **get_jit_kwargs(lineinfo))
    def lu_solve(
        state, parameters, drivers, cached_aux, base_state, t,
        _cubie_codegen_h, _cubie_codegen_a_ij, rhs, x, factor
    ):
        _cubie_codegen_j_1_0 = parameters[0] - state[2]
        _cubie_codegen_j_1_2 = -state[0]
        _cubie_codegen_lu_scale = precision(0.7886751294136047)*_cubie_codegen_h
        _cubie_codegen_lu_w_0_0 = precision(10)*_cubie_codegen_lu_scale + precision(1.0)
        _cubie_codegen_lu_w_0_1 = -(precision(10)*_cubie_codegen_lu_scale)
        _cubie_codegen_lu_w_1_0 = -(_cubie_codegen_j_1_0*_cubie_codegen_lu_scale)
        _cubie_codegen_lu_w_1_1 = _cubie_codegen_lu_scale + precision(1.0)
        _cubie_codegen_lu_w_1_2 = -(_cubie_codegen_j_1_2*_cubie_codegen_lu_scale)
        _cubie_codegen_lu_w_2_0 = -(_cubie_codegen_lu_scale*state[1])
        _cubie_codegen_lu_w_2_1 = -(_cubie_codegen_lu_scale*state[0])
        _cubie_codegen_lu_w_2_2 = precision(2.6666666666666665)*_cubie_codegen_lu_scale + precision(1.0)
        _cubie_codegen_lu_dmag_0 = math.fabs(_cubie_codegen_lu_w_0_0)
        factor[1] = _cubie_codegen_lu_w_0_1
        factor[4] = _cubie_codegen_lu_w_1_2
        _cubie_codegen_lu_dflr_0 = math.copysign(max(_cubie_codegen_lu_dmag_0, precision(1e-16)), _cubie_codegen_lu_w_0_0)
        factor[0] = (precision(1)/_cubie_codegen_lu_dflr_0)
        factor[2] = _cubie_codegen_lu_w_1_0*factor[0]
        factor[5] = _cubie_codegen_lu_w_2_0*factor[0]
        _cubie_codegen_lu_d_1 = _cubie_codegen_lu_w_1_1 - factor[1]*factor[2]
        _cubie_codegen_lu_y_1 = rhs[1] - factor[2]*rhs[0]
        _cubie_codegen_lu_dmag_1 = math.fabs(_cubie_codegen_lu_d_1)
        _cubie_codegen_lu_dflr_1 = math.copysign(max(_cubie_codegen_lu_dmag_1, precision(1e-16)), _cubie_codegen_lu_d_1)
        factor[3] = (precision(1)/_cubie_codegen_lu_dflr_1)
        factor[6] = factor[3]*(_cubie_codegen_lu_w_2_1 - factor[1]*factor[5])
        _cubie_codegen_lu_d_2 = _cubie_codegen_lu_w_2_2 - factor[4]*factor[6]
        _cubie_codegen_lu_y_2 = rhs[2] - _cubie_codegen_lu_y_1*factor[6] - factor[5]*rhs[0]
        _cubie_codegen_lu_dmag_2 = math.fabs(_cubie_codegen_lu_d_2)
        _cubie_codegen_lu_dflr_2 = math.copysign(max(_cubie_codegen_lu_dmag_2, precision(1e-16)), _cubie_codegen_lu_d_2)
        factor[7] = (precision(1)/_cubie_codegen_lu_dflr_2)
        _cubie_codegen_lu_xs_2 = _cubie_codegen_lu_y_2*factor[7]
        _cubie_codegen_lu_xs_1 = factor[3]*(_cubie_codegen_lu_y_1 - _cubie_codegen_lu_xs_2*factor[4])
        x[2] = _cubie_codegen_lu_xs_2
        _cubie_codegen_lu_xs_0 = factor[0]*(rhs[0] - _cubie_codegen_lu_xs_1*factor[1])
        x[1] = _cubie_codegen_lu_xs_1
        x[0] = _cubie_codegen_lu_xs_0
        return int32(0)
    return lu_solve
# Buffer sizes read by the helper registry
lu_solve_cached_scd8c35dcc3f58b01a730627fae41722ecc7038de659bc3e21147fe1246c3f9e1.aux_count = None
lu_solve_cached_scd8c35dcc3f58b01a730627fae41722ecc7038de659bc3e21147fe1246c3f9e1.lu_nnz = 8

# AUTO-GENERATED MASS-MATRIX APPLY FACTORY
def apply_mass_plain_s45f58289f1c0f7f2429191343b269d25f2088f32c2ade1928c07942e63c2a0e4(precision, lineinfo=None):
    """Auto-generated mass-matrix product.
    Computes out = M @ v. `out` must not alias `v`.
    """
    @cuda.jit(
        device=True,
        inline=True,
        **get_jit_kwargs(lineinfo))
    def apply_mass(v, out):
        out[0] = v[0]
        out[1] = v[1]
        out[2] = v[2]
    return apply_mass
# Buffer sizes read by the helper registry
apply_mass_plain_s45f58289f1c0f7f2429191343b269d25f2088f32c2ade1928c07942e63c2a0e4.aux_count = None
apply_mass_plain_s45f58289f1c0f7f2429191343b269d25f2088f32c2ade1928c07942e63c2a0e4.lu_nnz = None

# AUTO-GENERATED DIRECT LU SOLVE FACTORY
def lu_solve_cached_s13c3c618cb94a18c3d6560b20d6ae78f111fcbba3d2a8ce59390b1f41e599728(precision, lineinfo=None):
    """Auto-generated direct sparse LU solve.
    Solves (beta * M - gamma * a_ij * h * J) @ x = rhs with a
    static symbolic factorisation; beta and gamma are baked in
    as numeric literals and J is evaluated at
    state, auxiliaries from cached_aux.
    Returns device function:
      lu_solve(state, parameters, drivers, cached_aux, base_state,
               t, h, a_ij, rhs, x, factor) -> int32
    Pivots are magnitude-floored; always returns int32(0).
    rhs is read-only; x is written unconditionally.
    """
    @cuda.jit(
        device=True,
        inline=True,
        **get_jit_kwargs(lineinfo))
    def lu_solve(
        state, parameters, drivers, cached_aux, base_state, t,
        _cubie_codegen_h, _cubie_codegen_a_ij, rhs, x, factor
    ):
        _cubie_codegen_j_1_0 = parameters[0] - state[2]
        _cubie_codegen_j_1_2 = -state[0]
        _cubie_codegen_lu_scale = precision(0.2928932309150696)*_cubie_codegen_h
        _cubie_codegen_lu_w_0_0 = precision(10)*_cubie_codegen_lu_scale + precision(1.0)
        _cubie_codegen_lu_w_0_1 = -(precision(10)*_cubie_codegen_lu_scale)
        _cubie_codegen_lu_w_1_0 = -(_cubie_codegen_j_1_0*_cubie_codegen_lu_scale)
        _cubie_codegen_lu_w_1_1 = _cubie_codegen_lu_scale + precision(1.0)
        _cubie_codegen_lu_w_1_2 = -(_cubie_codegen_j_1_2*_cubie_codegen_lu_scale)
        _cubie_codegen_lu_w_2_0 = -(_cubie_codegen_lu_scale*state[1])
        _cubie_codegen_lu_w_2_1 = -(_cubie_codegen_lu_scale*state[0])
        _cubie_codegen_lu_w_2_2 = precision(2.6666666666666665)*_cubie_codegen_lu_scale + precision(1.0)
        _cubie_codegen_lu_dmag_0 = math.fabs(_cubie_codegen_lu_w_0_0)
        factor[1] = _cubie_codegen_lu_w_0_1
        factor[4] = _cubie_codegen_lu_w_1_2
        _cubie_codegen_lu_dflr_0 = math.copysign(max(_cubie_codegen_lu_dmag_0, precision(1e-16)), _cubie_codegen_lu_w_0_0)
        factor[0] = (precision(1)/_cubie_codegen_lu_dflr_0)
        factor[2] = _cubie_codegen_lu_w_1_0*factor[0]
        factor[5] = _cubie_codegen_lu_w_2_0*factor[0]
        _cubie_codegen_lu_d_1 = _cubie_codegen_lu_w_1_1 - factor[1]*factor[2]
        _cubie_codegen_lu_y_1 = rhs[1] - factor[2]*rhs[0]
        _cubie_codegen_lu_dmag_1 = math.fabs(_cubie_codegen_lu_d_1)
        _cubie_codegen_lu_dflr_1 = math.copysign(max(_cubie_codegen_lu_dmag_1, precision(1e-16)), _cubie_codegen_lu_d_1)
        factor[3] = (precision(1)/_cubie_codegen_lu_dflr_1)
        factor[6] = factor[3]*(_cubie_codegen_lu_w_2_1 - factor[1]*factor[5])
        _cubie_codegen_lu_d_2 = _cubie_codegen_lu_w_2_2 - factor[4]*factor[6]
        _cubie_codegen_lu_y_2 = rhs[2] - _cubie_codegen_lu_y_1*factor[6] - factor[5]*rhs[0]
        _cubie_codegen_lu_dmag_2 = math.fabs(_cubie_codegen_lu_d_2)
        _cubie_codegen_lu_dflr_2 = math.copysign(max(_cubie_codegen_lu_dmag_2, precision(1e-16)), _cubie_codegen_lu_d_2)
        factor[7] = (precision(1)/_cubie_codegen_lu_dflr_2)
        _cubie_codegen_lu_xs_2 = _cubie_codegen_lu_y_2*factor[7]
        _cubie_codegen_lu_xs_1 = factor[3]*(_cubie_codegen_lu_y_1 - _cubie_codegen_lu_xs_2*factor[4])
        x[2] = _cubie_codegen_lu_xs_2
        _cubie_codegen_lu_xs_0 = factor[0]*(rhs[0] - _cubie_codegen_lu_xs_1*factor[1])
        x[1] = _cubie_codegen_lu_xs_1
        x[0] = _cubie_codegen_lu_xs_0
        return int32(0)
    return lu_solve
# Buffer sizes read by the helper registry
lu_solve_cached_s13c3c618cb94a18c3d6560b20d6ae78f111fcbba3d2a8ce59390b1f41e599728.aux_count = None
lu_solve_cached_s13c3c618cb94a18c3d6560b20d6ae78f111fcbba3d2a8ce59390b1f41e599728.lu_nnz = 8

# AUTO-GENERATED DIRECT LU SOLVE FACTORY
def lu_solve_cached_s0f658551049aa95dda2ed03d77b6713b11179c99f196b3ceddf61d347651d5a4(precision, lineinfo=None):
    """Auto-generated direct sparse LU solve.
    Solves (beta * M - gamma * a_ij * h * J) @ x = rhs with a
    static symbolic factorisation; beta and gamma are baked in
    as numeric literals and J is evaluated at
    state, auxiliaries from cached_aux.
    Returns device function:
      lu_solve(state, parameters, drivers, cached_aux, base_state,
               t, h, a_ij, rhs, x, factor) -> int32
    Pivots are magnitude-floored; always returns int32(0).
    rhs is read-only; x is written unconditionally.
    """
    @cuda.jit(
        device=True,
        inline=True,
        **get_jit_kwargs(lineinfo))
    def lu_solve(
        state, parameters, drivers, cached_aux, base_state, t,
        _cubie_codegen_h, _cubie_codegen_a_ij, rhs, x, factor
    ):
        _cubie_codegen_j_1_0 = parameters[0] - state[2]
        _cubie_codegen_j_1_2 = -state[0]
        _cubie_codegen_lu_scale = precision(0.3333333432674408)*_cubie_codegen_h
        _cubie_codegen_lu_w_0_0 = precision(10)*_cubie_codegen_lu_scale + precision(1.0)
        _cubie_codegen_lu_w_0_1 = -(precision(10)*_cubie_codegen_lu_scale)
        _cubie_codegen_lu_w_1_0 = -(_cubie_codegen_j_1_0*_cubie_codegen_lu_scale)
        _cubie_codegen_lu_w_1_1 = _cubie_codegen_lu_scale + precision(1.0)
        _cubie_codegen_lu_w_1_2 = -(_cubie_codegen_j_1_2*_cubie_codegen_lu_scale)
        _cubie_codegen_lu_w_2_0 = -(_cubie_codegen_lu_scale*state[1])
        _cubie_codegen_lu_w_2_1 = -(_cubie_codegen_lu_scale*state[0])
        _cubie_codegen_lu_w_2_2 = precision(2.6666666666666665)*_cubie_codegen_lu_scale + precision(1.0)
        _cubie_codegen_lu_dmag_0 = math.fabs(_cubie_codegen_lu_w_0_0)
        factor[1] = _cubie_codegen_lu_w_0_1
        factor[4] = _cubie_codegen_lu_w_1_2
        _cubie_codegen_lu_dflr_0 = math.copysign(max(_cubie_codegen_lu_dmag_0, precision(1e-16)), _cubie_codegen_lu_w_0_0)
        factor[0] = (precision(1)/_cubie_codegen_lu_dflr_0)
        factor[2] = _cubie_codegen_lu_w_1_0*factor[0]
        factor[5] = _cubie_codegen_lu_w_2_0*factor[0]
        _cubie_codegen_lu_d_1 = _cubie_codegen_lu_w_1_1 - factor[1]*factor[2]
        _cubie_codegen_lu_y_1 = rhs[1] - factor[2]*rhs[0]
        _cubie_codegen_lu_dmag_1 = math.fabs(_cubie_codegen_lu_d_1)
        _cubie_codegen_lu_dflr_1 = math.copysign(max(_cubie_codegen_lu_dmag_1, precision(1e-16)), _cubie_codegen_lu_d_1)
        factor[3] = (precision(1)/_cubie_codegen_lu_dflr_1)
        factor[6] = factor[3]*(_cubie_codegen_lu_w_2_1 - factor[1]*factor[5])
        _cubie_codegen_lu_d_2 = _cubie_codegen_lu_w_2_2 - factor[4]*factor[6]
        _cubie_codegen_lu_y_2 = rhs[2] - _cubie_codegen_lu_y_1*factor[6] - factor[5]*rhs[0]
        _cubie_codegen_lu_dmag_2 = math.fabs(_cubie_codegen_lu_d_2)
        _cubie_codegen_lu_dflr_2 = math.copysign(max(_cubie_codegen_lu_dmag_2, precision(1e-16)), _cubie_codegen_lu_d_2)
        factor[7] = (precision(1)/_cubie_codegen_lu_dflr_2)
        _cubie_codegen_lu_xs_2 = _cubie_codegen_lu_y_2*factor[7]
        _cubie_codegen_lu_xs_1 = factor[3]*(_cubie_codegen_lu_y_1 - _cubie_codegen_lu_xs_2*factor[4])
        x[2] = _cubie_codegen_lu_xs_2
        _cubie_codegen_lu_xs_0 = factor[0]*(rhs[0] - _cubie_codegen_lu_xs_1*factor[1])
        x[1] = _cubie_codegen_lu_xs_1
        x[0] = _cubie_codegen_lu_xs_0
        return int32(0)
    return lu_solve
# Buffer sizes read by the helper registry
lu_solve_cached_s0f658551049aa95dda2ed03d77b6713b11179c99f196b3ceddf61d347651d5a4.aux_count = None
lu_solve_cached_s0f658551049aa95dda2ed03d77b6713b11179c99f196b3ceddf61d347651d5a4.lu_nnz = 8
