"""Store generated CUDA factory source on disk."""

from importlib import util
from typing import Callable, Optional, Tuple

from cubie._utils import package_source_hash
from cubie.cache_root import get_cache_root
from cubie.time_logger import default_timelogger


def _salted_hash(fn_hash) -> str:
    """Combine a system definition hash with the package source hash.

    The stored file hash carries both, so generated source is
    regenerated when the codegen machinery changes, not only when the
    system definition does.
    """
    return f"{fn_hash}-{package_source_hash()[:16]}"

HEADER = ("\n# Generated by CuBIE. Edit the system definition instead.\n"
          "from cubie.cuda_simsafe import cuda, int32\n"
          "import math\n"
          "from cubie.cuda_simsafe import *\n"
          "\n")


class ODEFile:
    """Cache generated ODE functions on disk and reload them when possible."""

    def __init__(self, system_name: str, fn_hash: int) -> None:
        """Initialise a cache file for a system definition.

        Parameters
        ----------
        system_name
            Name used when constructing the generated module filename.
        fn_hash
            Hash representing the symbolic system definition; a
            prefix of it names the file, one file per identity.
        """
        system_dir = get_cache_root() / system_name
        system_dir.mkdir(parents=True, exist_ok=True)
        variant = str(fn_hash)[:10]
        self.file_path = system_dir / f"{system_name}_{variant}.py"
        self.fn_hash = fn_hash
        self._cache_notification_printed = False
        self._init_file(fn_hash)

    def _init_file(self, fn_hash: int) -> bool:
        """Create a new generated file when the stored hash is stale.

        Parameters
        ----------
        fn_hash
            Hash representing the symbolic system definition.

        Returns
        -------
        bool
            ``True`` when the file was (re)created, ``False`` otherwise.
        """
        if not self.cached_file_valid(fn_hash):
            with open(self.file_path, "w", encoding="utf-8") as f:
                f.write(f"#{_salted_hash(fn_hash)}")
                f.write("\n")
                f.write(HEADER)
            return True
        return False

    def cached_file_valid(self, fn_hash: int) -> bool:
        """Check that the cache file exists and stores the expected hash.

        Parameters
        ----------
        fn_hash
            Hash representing the symbolic system definition.

        Returns
        -------
        bool
            ``True`` when the stored hash matches ``fn_hash`` combined
            with the current package source hash.
        """
        if self.file_path.exists():
            with open(self.file_path, "r", encoding="utf-8") as f:
                existing_hash = f.readline().strip().lstrip("#")
                if existing_hash == _salted_hash(fn_hash):
                    return True
        return False

    def function_is_cached(self, func_name: str) -> bool:
        """Check if a function exists in the cache file.

        Parameters
        ----------
        func_name
            Name of the function to check.

        Returns
        -------
        bool
            ``True`` if the function is properly defined in the cache file.
        """
        if not self.file_path.exists():
            return False
        text = self.file_path.read_text()
        has_function = f"def {func_name}(" in text
        if has_function:
            lines = text.split('\n')
            in_function = False
            func_indent = None
            has_return = False
            for line in lines:
                if f"def {func_name}(" in line:
                    in_function = True
                    func_indent = len(line) - len(line.lstrip())
                elif in_function:
                    stripped = line.lstrip()
                    if not stripped:
                        continue
                    current_indent = len(line) - len(stripped)
                    if current_indent <= func_indent and stripped.startswith(
                        "def "
                    ):
                        break
                    if current_indent == func_indent + 4 and stripped.startswith(
                        "return "
                    ):
                        has_return = True
                        break
            if not has_return:
                has_function = False
        return has_function

    def _import_function(
        self,
        func_name: str,
        injections: Optional[dict[str, Callable]] = None,
    ) -> Callable:
        """Import ``func_name`` from the generated module.

        Parameters
        ----------
        func_name
            Name of the generated function to import.
        injections
            Callables set as module attributes after import so the
            generated factory can resolve them by name, e.g. user
            device functions called from the generated source.

        Returns
        -------
        Callable
            The imported factory function.
        """
        spec = util.spec_from_file_location(func_name, self.file_path)
        module = util.module_from_spec(spec)
        spec.loader.exec_module(module)
        for name, obj in (injections or {}).items():
            setattr(module, name, obj)
        return getattr(module, func_name)

    def import_function(
        self,
        func_name: str,
        code_lines: Optional[str] = None,
        injections: Optional[dict[str, Callable]] = None,
    ) -> Tuple[Callable, bool]:
        """Import a generated function, generating it when absent.

        Parameters
        ----------
        func_name
            Name of the factory function to import.
        code_lines
            Source code used to generate the function when it is not cached.
        injections
            Callables set as attributes on the generated module so the
            factory can resolve them by name, e.g. user device
            functions called from the generated source.

        Returns
        -------
        Tuple[Callable, bool]
            Tuple of (imported factory function, was_cached). was_cached is
            True if the function was found in cache, False if it was generated.

        Raises
        ------
        ValueError
            Raised when the function is absent from the cache and
            ``code_lines`` is ``None``.
        """
        if not self.cached_file_valid(self.fn_hash):
            self._init_file(self.fn_hash)
        
        was_cached = self.function_is_cached(func_name)
        
        if was_cached:
            # Print one-time cache notification via TimeLogger
            if not self._cache_notification_printed:
                default_timelogger.print_message(
                    f"Existing codegen file found at: {self.file_path}. "
                    f"Skipping steps that have functions already cached."
                )
                self._cache_notification_printed = True
        else:
            if code_lines is None:
                raise ValueError(
                    f"{func_name} not found in cache and no code provided."
                )
            self.add_function(code_lines)

        return self._import_function(func_name, injections), was_cached

    def add_function(self, printed_code: str) -> None:
        """Append generated code to the cache file.

        Parameters
        ----------
        printed_code
            Generated source code for the function.
        """
        with open(self.file_path, "a", encoding="utf-8") as f:
            f.write(printed_code)

