"""Tests for cubie.odesystems.symbolic.odefile."""

from __future__ import annotations

import uuid

import pytest

from cubie.odesystems.symbolic.odefile import (
    HEADER,
    ODEFile,
    _salted_hash,
)
from cubie._utils import package_source_hash


def _simple_code(func_name: str) -> str:
    """Return minimal valid factory function source code."""
    base = func_name.replace("_factory", "")
    return (
        f"def {func_name}():\n"
        f"    def {base}():\n"
        "        return 1\n"
        f"    return {base}\n"
    )


# ── __init__ ──────────────────────────────────────────────────── #

def test_init_creates_system_directory(codegen_dir):
    """__init__ creates the system subdirectory under the cache root."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 12345)
    assert odf.file_path.parent.exists()
    assert odf.file_path.parent.name == name


def test_init_sets_file_path(codegen_dir):
    """file_path carries the name and a hash-prefixed variant."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 99)
    assert odf.file_path.name == f"{name}_99.py"
    assert odf.file_path.parent.name == name


def test_distinct_hashes_use_distinct_files(codegen_dir):
    """Two source identities coexist without rewriting each other."""
    name = f"test_{uuid.uuid4().hex}"
    first = ODEFile(name, "aaaaaaaaaaaaaaaa")
    second = ODEFile(name, "bbbbbbbbbbbbbbbb")
    assert first.file_path != second.file_path
    first.add_function("def f_marker():\n    return 1\n")
    # Re-opening the first identity keeps its cached function.
    reopened = ODEFile(name, "aaaaaaaaaaaaaaaa")
    assert reopened.function_is_cached("f_marker")


def test_init_calls_init_file(codegen_dir):
    """__init__ writes the file with the salted hash and header."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 42)
    text = odf.file_path.read_text(encoding="utf-8")
    assert text.startswith(f"#{_salted_hash(42)}\n")
    assert "# Generated by CuBIE." in text


def test_salted_hash_includes_package_source_hash():
    """The stored hash combines fn_hash with the package source hash."""
    assert _salted_hash(42) == f"42-{package_source_hash()[:16]}"


def test_cached_file_valid_false_on_stale_package_salt(codegen_dir):
    """A file written under different package source is invalid."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 777)
    stale = f"#777-{'0' * 16}\n{HEADER}"
    odf.file_path.write_text(stale, encoding="utf-8")
    assert odf.cached_file_valid(777) is False


# ── _init_file ────────────────────────────────────────────────── #

def test_init_file_returns_true_when_created(codegen_dir):
    """_init_file returns True when file was (re)created."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    # Change hash so next _init_file considers cache invalid
    result = odf._init_file(999)
    assert result is True


def test_init_file_returns_false_when_valid(codegen_dir):
    """_init_file returns False when cache is already valid."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    result = odf._init_file(1)
    assert result is False


# ── cached_file_valid ─────────────────────────────────────────── #

def test_cached_file_valid_false_when_missing(codegen_dir, tmp_path):
    """Returns False when file does not exist."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    odf.file_path.unlink()
    assert odf.cached_file_valid(1) is False


def test_cached_file_valid_true_on_match(codegen_dir):
    """Returns True when stored hash matches."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 777)
    assert odf.cached_file_valid(777) is True


def test_cached_file_valid_false_on_mismatch(codegen_dir):
    """Returns False when stored hash differs."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 777)
    assert odf.cached_file_valid(888) is False


# ── function_is_cached ────────────────────────────────────────── #

def test_function_is_cached_false_no_file(codegen_dir):
    """Returns False when file doesn't exist."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    odf.file_path.unlink()
    assert odf.function_is_cached("foo_factory") is False


def test_function_is_cached_false_no_def(codegen_dir):
    """Returns False when function def not found."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    assert odf.function_is_cached("nonexistent_factory") is False


def test_function_is_cached_true_with_return(codegen_dir):
    """Returns True when function def found with return at correct indent."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    odf.add_function(_simple_code("foo_factory"))
    assert odf.function_is_cached("foo_factory") is True


def test_function_is_cached_false_no_return(codegen_dir):
    """Returns False when function def found but no return statement."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    odf.add_function("def broken_factory():\n    pass\n")
    assert odf.function_is_cached("broken_factory") is False


# ── import_function ───────────────────────────────────────────── #

def test_import_function_generates_and_returns(codegen_dir):
    """import_function generates code and returns (function, False)."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    fn, was_cached = odf.import_function(
        "foo_factory",
        _simple_code("foo_factory"),
    )
    assert fn()() == 1
    assert was_cached is False


def test_import_function_returns_cached(codegen_dir):
    """import_function returns (function, True) on second call."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    odf.import_function("foo_factory", _simple_code("foo_factory"))
    fn, was_cached = odf.import_function("foo_factory")
    assert fn()() == 1
    assert was_cached is True


def test_import_function_raises_without_code(codegen_dir):
    """import_function raises ValueError when not cached and no code."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    with pytest.raises(ValueError, match="not found in cache"):
        odf.import_function("missing_factory")


def test_import_function_reinits_on_hash_change(codegen_dir):
    """import_function reinitializes file when cache invalid."""
    name = f"test_{uuid.uuid4().hex}"
    odf1 = ODEFile(name, "hash1")
    odf1.import_function("foo_factory", _simple_code("foo_factory"))
    # New instance with different hash
    odf2 = ODEFile(name, "hash2")
    with pytest.raises(ValueError):
        odf2.import_function("foo_factory")
    fn, was_cached = odf2.import_function(
        "foo_factory",
        _simple_code("foo_factory"),
    )
    assert fn()() == 1
    assert was_cached is False


def test_import_function_cache_notification_printed_once(codegen_dir):
    """One-time cache notification flag set on first cached hit."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    odf.import_function("foo_factory", _simple_code("foo_factory"))
    assert odf._cache_notification_printed is False
    odf.import_function("foo_factory")
    assert odf._cache_notification_printed is True
    # Second call doesn't reset
    odf.import_function("foo_factory")
    assert odf._cache_notification_printed is True


# ── add_function ──────────────────────────────────────────────── #

def test_add_function_appends_code(codegen_dir):
    """add_function appends code to the cache file."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    code = _simple_code("bar_factory")
    odf.add_function(code)
    text = odf.file_path.read_text(encoding="utf-8")
    assert "def bar_factory()" in text


# ── _import_function ──────────────────────────────────────────── #

def test_import_function_loads_from_module(codegen_dir):
    """_import_function imports a callable from the generated module."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    odf.add_function(_simple_code("baz_factory"))
    fn = odf._import_function("baz_factory")
    assert fn()() == 1


# ── HEADER constant ───────────────────────────────────────────── #

def test_header_contains_required_imports():
    """HEADER includes hub, math, and cuda_simsafe star imports."""
    assert "from cubie.cuda_simsafe import cuda, int32" in HEADER
    assert "import math" in HEADER
    assert "from cubie.cuda_simsafe import *" in HEADER


def test_header_contains_autogen_notice():
    """HEADER identifies generated source."""
    assert "# Generated by CuBIE." in HEADER


# ── Multiple functions in same file ───────────────────────────── #

def test_multiple_factories_coexist(codegen_dir):
    """Multiple functions can be appended and imported from same file."""
    name = f"test_{uuid.uuid4().hex}"
    odf = ODEFile(name, 1)
    odf.import_function("foo_factory", _simple_code("foo_factory"))
    odf.import_function("bar_factory", _simple_code("bar_factory"))
    fn1, _ = odf.import_function("foo_factory")
    fn2, _ = odf.import_function("bar_factory")
    assert fn1()() == 1
    assert fn2()() == 1
