"""Lightweight expression engine for symbolic CUDA codegen.

Hash-consed expression IR plus the compute passes codegen needs:
conversion from SymPy (:mod:`from_sympy`), differentiation and
substitution (:mod:`expr`), assignment-list transforms
(:mod:`assignments`), and source emission (:mod:`printer`). SymPy is
the parse layer for string and SymPy input; expressions convert to
the IR at the parse boundary and every downstream pass runs on it.
"""

from cubie.odesystems.symbolic.engine.expr import (
    Add,
    Arr,
    BoolConst,
    BoolOp,
    Call,
    DifferentiationError,
    Expr,
    FALSE,
    Local,
    Mul,
    NEG_ONE,
    Num,
    ONE,
    Piecewise,
    Pow,
    Rel,
    Sym,
    TRUE,
    ZERO,
    add,
    arr,
    bool_op,
    call,
    count_ops,
    diff,
    div,
    free_atoms,
    is_one,
    is_zero,
    local,
    mul,
    neg,
    num,
    piecewise,
    pow_,
    rel,
    sub,
    sym,
    xreplace,
)
from cubie.odesystems.symbolic.engine.assignments import (
    cse_and_stack,
    prune_unused,
    topological_sort,
)
from cubie.odesystems.symbolic.engine.from_sympy import (
    ConversionError,
    convert_assignments,
    derivative_name_map,
    from_sympy,
    to_sympy,
)
from cubie.odesystems.symbolic.engine.printer import (
    CUDA_FUNCTIONS,
    IRPrinter,
    print_cuda,
    print_cuda_multiple,
)

__all__ = [
    "Add",
    "Arr",
    "BoolConst",
    "BoolOp",
    "Call",
    "ConversionError",
    "CUDA_FUNCTIONS",
    "DifferentiationError",
    "Expr",
    "FALSE",
    "IRPrinter",
    "Local",
    "Mul",
    "NEG_ONE",
    "Num",
    "ONE",
    "Piecewise",
    "Pow",
    "Rel",
    "Sym",
    "TRUE",
    "ZERO",
    "add",
    "arr",
    "bool_op",
    "call",
    "convert_assignments",
    "count_ops",
    "cse_and_stack",
    "derivative_name_map",
    "diff",
    "div",
    "free_atoms",
    "is_one",
    "is_zero",
    "local",
    "from_sympy",
    "mul",
    "neg",
    "num",
    "piecewise",
    "pow_",
    "prune_unused",
    "print_cuda",
    "print_cuda_multiple",
    "rel",
    "sub",
    "sym",
    "to_sympy",
    "topological_sort",
    "xreplace",
]
